module-name: template-operator
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/template-operator:0.1.0
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
