apiVersion: v1
kind: Namespace
metadata:
  name: manifest-redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-redis-config
  namespace: manifest-redis
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-redis-deployment
  namespace: manifest-redis
spec:
  selector:
    matchLabels:
      control-plane: redis-deployment
  template:
    metadata:
      labels:
        control-plane: redis-deployment
    spec:
      containers:
        - name: redis
          image: redis:5.0.4
          imagePullPolicy: Always
          command:
            - redis-server
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "0.1"
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
            - mountPath: /redis-master
              name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: sample-redis-config
            items:
              - key: redis-config
                path: redis.conf
